1. Scenario: You have a list of integers, and you need to find the maximum
value in the list.
a. Question: How would you find the maximum value from the
following list?

In [2]:
num_list = [4,7,8,10,3]
max_num = max(num_list)
print("The max number is: ", max_num)

The max number is:  10


2. Scenario: You need to concatenate a list of strings into a single string,
with each string separated by a comma.
a. Question: How would you combine the following list of strings into
a single strig?

In [4]:
string_1 = "My name is Shikha"
string_2 = "I live in Texas"
string_3 = "I am learning Python"
concatenate_string = string_1 + ", " + string_2 + ", "+ string_3
print(concatenate_string)

My name is Shikha, I live in Texas, I am learning Python


3. Scenario: You have a dictionary where the keys are names and the
values are ages. You need to retrieve the age of a specific person.
a. Question: How would you get the age of "Dev" from the following
dictionary?

In [6]:
teacher_age = {"Dev":24, "Ram":35, "Shyam":45, "Hari":25}
print(teacher_age["Dev"])

24


4. Scenario: You need to remove duplicate elements from a list while
preserving the original order of elements.
a. Question: How would you remove duplicates from the following
list?

In [8]:
my_list = [1,2,3,4,4,5]
unique_list= list(set(my_list))
print(unique_list)

[1, 2, 3, 4, 5]


5. Scenario: You have a NumPy array and need to compute the sum of all
its elements.
a. Question: How would you find the sum of elements in the
following NumPy array?

In [10]:
import numpy as np
list_array = np.array([1,2,3,4,5])
total_sum = np.sum(list_array)
print(total_sum)


15


6. Scenario: You have a 2D NumPy array and need to get the maximum
value from each column.
a. Question: How would you find the maximum values for each
column in the following array?

import numpy as np
array_2d = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
max_vales = np.max(array_2d, axis=0)
print(array_2d.shape)
print(max_vales)

7. Scenario: You have a DataFrame and need to sort it by a specific column.
a. Question: How would you sort the DataFrame by the "Age"
column?

In [14]:
import pandas as pd
data = {
  "candidate_name": ["Bikash", "Shikha", "Roshan", "Sunita", "Sunil","Shweta"],
  "age": [40, 36, 44, 40, 43, 41]
}
#load data into a DataFrame object:
df = pd.DataFrame(data)
sorted_df = df.sort_values(by=['age'])
print(sorted_df)

  candidate_name  age
1         Shikha   36
0         Bikash   40
3         Sunita   40
5         Shweta   41
4          Sunil   43
2         Roshan   44


8. Scenario: You need to calculate the total sum of a column in a
DataFrame.
a. Question: How would you find the sum of the "Sales" column?

In [42]:
import pandas as pd
data = {
  "product_name": ["product A", "product B", "product C", "product D"],
  "sales": [500, 200, 400, 800]
}
#load data into a DataFrame object:
df = pd.DataFrame(data)
total_sum = df["sales"].sum()
print ("Total_sales:",total_sum )

Total_sales: 1900


9. Scenario: You need to check if a variable is of type int.
a. Question: How would you verify if a variable x is an integer?


In [47]:
my_variable = 42
print(type(my_variable))

<class 'int'>


10.Scenario: You have a list of mixed types and need to create separate lists
for integers, floats, and strings.
a. Question: How would you categorize the following mixed list into
different types?


In [13]:
list = [1,"Sanaya",2, "Bikash", 1.45 ,"Shikha", 2.68]
integers = []
floats = []
string = []
for item in list:
    if isinstance(item, int):
        integers.append(item)
    elif isinstance(item, float):
        floats.append(item)
    elif isinstance(item, str):
        string.append(item)
print("integers:", integers)
print("floats:", floats)
print("string:", string)

integers: [1, 2]
floats: [1.45, 2.68]
string: ['Sanaya', 'Bikash', 'Shikha']


11.Scenario: You are given a string of comma-separated numbers. You
need to convert this string into a list of integers.
a. Question: How would you achieve this conversion?

In [16]:
num_string = "1, 2, 3, 9, 5, 11"
int_list = num_string.split(", ")
print(int_list)

['1', '2', '3', '9', '5', '11']


12.Scenario: You need to reverse the words in a sentence while keeping the
order of the words intact.
a. Question: How would you reverse each word in the following
sentence?


In [27]:
str_name = "My name is Shikha"
words = str_name.split()
reversed_words = [word[::-1] for word in words]
reversed_sentence = " ".join(reversed_words)
print(reversed_sentence)

yM eman si ahkihS


13.Scenario: You need to combine two lists into a dictionary where the
elements of the first list are keys and the elements of the second list are
values.
a. Question: How would you combine the following lists into a
dictionary?


In [32]:
keys = ["name", "age", "state"]
values = ["Shikha", 35, "TX"]
combined_dict = dict(zip(keys,values))
print(combined_dict)

{'name': 'Shikha', 'age': 35, 'state': 'TX'}


14.Scenario: You are given a list of tuples where each tuple contains a name
and an age. You need to sort this list by age
a. Question: How would you sort the following list of tuples by age?

In [47]:
name_age_tuple = [(40, "Bikash"), (35, "Shikha"), (44, "Sunil"), (41, "Sweta")]
name_age_tuple.sort()
print(name_age_tuple)

[(35, 'Shikha'), (40, 'Bikash'), (41, 'Sweta'), (44, 'Sunil')]


15.Scenario: You have a 2D NumPy array and need to calculate the mean
value of each row.
a. Question: How would you compute the mean value for each row
in the following array?

In [51]:
import numpy as np
array_2d = np.array([[7, 8, 9],
                     [4, 5, 6],
                     [1, 2, 3]])
row_means = np.mean(array_2d, axis=1)
print(row_means)

[8. 5. 2.]


16.Scenario: You need to create a NumPy array of size 10 filled with zeros,
and then set the fifth element to 5.
a. Question: How would you create and modify the array as
described?

In [64]:
import numpy as np
num_array = np.array([22, 33, 44, 55, 0, 20, 35, 99, 0, 10])
print(num_array)
num_array[4] =5
print(num_array)

[22 33 44 55  0 20 35 99  0 10]
[22 33 44 55  5 20 35 99  0 10]


17.Scenario: You have a DataFrame and need to find the median of a
numeric column.
a. Question: How would you find the median of the "Scores" column
in the following DataFrame?

In [83]:
import pandas as pd
data = {
    "scores": [25, 55, 12, 27, 35]
}
df = pd.DataFrame(data)
medians = df.median()
print(medians)

scores    27.0
dtype: float64


18.Scenario: You need to filter rows where the value in the "Sales" column
is above 100 and then sort these rows by "Date" in descending order.
a. Question: How would you filter and sort the DataFrame based on
the given criteria?

In [106]:
import pandas as pd
data = {
    "Sales": [100, 300, 200, 80, 30],
    "Date": ["2024-01-10", "2024-02-23", "2024-05-01", "2024-09-10", "2024-07-19"]    
}
df = pd.DataFrame(data)
filter_df = df[df["Sales"]> 100]
sort_df = filter_df.sort_values("Date", ascending = False )
print(sort_df)

   Sales        Date
2    200  2024-05-01
1    300  2024-02-23


19.Scenario: You have a string containing a number and need to convert it
to an integer. Additionally, handle the case where the string might not
represent a valid integer.
a. Question: How would you safely convert the string "42" to an
integer and handle invalid cases?


In [134]:
str_int = "abc"
try:
    int_num = int(str_int)
    print(int_num)
except ValueError:
    print("This is not an integer.")

This is not an integer.


20.Scenario: You have a list containing different data types, and you want
to separate out all the strings.
a. Question: How would you extract all string elements from the
following list?

In [137]:
list = [1,"Sanaya",2, "Bikash", 1.45 ,"Shikha", 2.68]
string = []
for item in list:
    if isinstance(item, str):
        string.append(item)
print("string:", string)

string: ['Sanaya', 'Bikash', 'Shikha']
